# Generated by Django 3.2.5 on 2021-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='old_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='price_difference',
            field=models.FloatField(default=0),
        ),
    ]
